### ISSUE TITLE
cannot import name Environment

### ISSUE THREAD

**Issue by 1nc00r3ct** [synhack/mercure#73]
![mercure ex error](https://user-images.githubusercontent.com/30824002/29060044-c34b1780-7c35-11e7-9ff9-16edb4786966.png)

Hi, once the server is up and running I am getting the following error as shown in the screenshot, I have tried renaming the Jinja file but no use. Could you help me out?

Request Method: | GET
-- | --
http://127.0.0.1:8000/en/accounts/login/?next=/en/campaigns/
1.10.7
ImportError
cannot import name Environment
C:\Users\admin\Desktop\mercure-master\mercure\jinja2.py in <module>, line 6

**Comment by julienlh** [comment]
Hi ! 

Just asking, did you install all packages in "requirements.txt" ?
-> pip install --upgrade -r requirements.txt

After this command, let me know if the problem persists.

If the problem persists, we hardly preconize to be on Linux. Moreover a docker image is ready-to-use : 
-> https://github.com/synhack/mercure#docker-quickstart

**Comment by 1nc00r3ct** [comment]
I have followed exactly how it mentioned in the guide. I was able to start the server but the issue is as mentioned in the screenshot.

**Comment by julienlh** [comment]
The guide was made for Linux (you can use Virtual Machine or Docker Image to fix the problem easily). 

Without debug informations, we can't find the bug. 
First, can you run : 
-> pip list

**Comment by 1nc00r3ct** [comment]
Hi, finally it worked but couldn't be able to send any emails. It is showing as mail sent but couldn't find any. Could you please provide walkthrough?

**Comment by julienlh** [comment]
Did you correctly configure setting values with environment variable (email server, secret_key, url,  email user, email password ..) ? 
-> values example : https://github.com/synhack/mercure#sample-deployment
-> required values  : https://github.com/synhack/mercure#available-configuration

Did you set "DEBUG = False" ? (If not, email is print in the terminal)
After setting this value, check in your "sent email" to know if the email was send or not.
