### ISSUE TITLE
hi sir 

### ISSUE THREAD

**Issue by samichow** [synhack/mercure#89]
how can i use this file in windows please help me

**Comment by julienlh** [comment]
The guide was made for Linux (you can use Virtual Machine or Docker Image to fix the problem easily).

You can also see the previous tickets : 
https://github.com/synhack/mercure/issues/73
https://github.com/synhack/mercure/issues/65

**Comment by y0no** [comment]
To work with Windows, you need to install python3 from official website with "pip" to get the required libraries. Installation guide is made for Linux but can be followed for Windows.

Also, you can use docker to execute Mercure without python, django, etc. on your machine
